#!/bin/bash
set -e
set -o pipefail

if [ -d "$NEXUS_DATA" -a "$(stat -c '%U' "$NEXUS_DATA" 2>/dev/null)" = "root" ]; then
  chown nexus "$NEXUS_DATA"
  chmod o-rwx "$NEXUS_DATA"
fi

if [ "$1" = 'nexus' ]; then
  readonly nexus_conf_defaults="$NEXUS_HOME/etc"

  if [ ! -d "$NEXUS_CONF" ]; then
    chroot --userspec=nexus / mkdir -p "$NEXUS_CONF"
    chroot --userspec=nexus / cp -a --no-clobber "$nexus_conf_defaults/." "$NEXUS_CONF"
    chmod 644 "$NEXUS_CONF"/*
  fi

  source /java-opts.sh
  export INSTALL4J_ADD_VM_PARAMS="$JAVA_OPTS"

   exec su_exec nexus java "$NEXUS_HOME/bin/nexus" run
else
  exec "$@"
fi
