#!/bin/bash
set -e
set -o pipefail

if [ -d "$NEXUS_DATA" -a "$(stat -c '%U' "$NEXUS_DATA" 2>/dev/null)" = "root" ]; then
  chown nexus "$NEXUS_DATA"
  chmod o-rwx "$NEXUS_DATA"
fi

if [ "$1" = 'nexus' ]; then
  readonly nexus_data_conf="$NEXUS_DATA/conf"
  chroot --userspec=nexus / mkdir -p "$nexus_data_conf"

  # the -Dapplication-conf nexus setting only works for security.xml
  # https://issues.sonatype.org/browse/NEXUS-4039
  # so symlink any files in NEXUS_CONF into the data/etc directory
  for file in "$NEXUS_CONF"/*; do
    [ -e "$file" ] || continue
    filename=$(basename "$file")
    if [ -f "$nexus_data_conf/$filename" ]; then
      chroot --userspec=nexus / mv "$nexus_data_conf/$filename" "$nexus_data_conf/$filename.bak"
    fi
    chroot --userspec=nexus / ln -s "$file" "$nexus_data_conf/$filename"
  done

  source /java-opts.sh

  exec su_exec nexus java \
    -Dnexus-work="${NEXUS_DATA}" \
    -Dnexus-webapp-context-path="${NEXUS_CONTEXT_PATH}" \
    -cp 'conf/:lib/*' \
    ${JAVA_OPTS} \
    org.sonatype.nexus.bootstrap.Launcher ./conf/jetty.xml ./conf/jetty-requestlog.xml
else
  exec "$@"
fi
