load("//scripts/versions:versions.bzl", "version_shell_script")

version_shell_script(
  name = "versions",
  visibility = ["//visibility:public"],
)

filegroup(
  name = "template",
  srcs = ["versions.sh.tpl"],
  visibility = ["//visibility:public"],
)
