#!/bin/bash

CASSANDRA_VERSION=%{CASSANDRA_VERSION}
CASSANDRA_DEB_VERSION=%{CASSANDRA_DEB_VERSION}

DNSMASQ_VERSION=%{DNSMASQ_VERSION}
DNSMASQ_DEB_VERSION=%{DNSMASQ_DEB_VERSION}

ENVOY_VERSION=%{ENVOY_VERSION}

ERLANG_VERSION=%{ERLANG_VERSION}
ERLANG_DEB_VERSION=%{ERLANG_DEB_VERSION}

GERRIT_VERSION=%{GERRIT_VERSION}

GRAFANA_VERSION=%{GRAFANA_VERSION}
GRAFANA_DEB_VERSION=%{GRAFANA_DEB_VERSION}

JAVA_8_VERSION=%{JAVA_8_VERSION}
ZULU_8_VERSION=%{ZULU_8_VERSION}
JAVA_11_VERSION=%{JAVA_11_VERSION}
ZULU_11_VERSION=%{ZULU_11_VERSION}
JAVA_17_VERSION=%{JAVA_17_VERSION}
ZULU_17_VERSION=%{ZULU_17_VERSION}
GRAAL_VERSION=%{GRAAL_VERSION}

JENKINS_VERSION=%{JENKINS_VERSION}
JENKINS_SWARM_VERSION=%{JENKINS_SWARM_VERSION}

KAFKA_VERSION=%{KAFKA_VERSION}

MAVEN_VERSION=%{MAVEN_VERSION}

NGINX_VERSION=%{NGINX_VERSION}
NGINX_DEB_VERSION=%{NGINX_DEB_VERSION}

NODEJS_VERSION=%{NODEJS_VERSION}

PHP_VERSION=%{PHP_VERSION}
PHP_DEB_VERSION=%{PHP_DEB_VERSION}

POSTGRESQL_MAJOR_VERSION=%{POSTGRESQL_MAJOR_VERSION}
POSTGRESQL_VERSION=%{POSTGRESQL_VERSION}
POSTGRESQL_DEB_VERSION=%{POSTGRESQL_DEB_VERSION}
POSTGIS_MINOR_VERSION=%{POSTGIS_MINOR_VERSION}
POSTGIS_VERSION=%{POSTGIS_VERSION}
POSTGIS_CONTAINER_VERSION=%{POSTGIS_CONTAINER_VERSION}
POSTGIS_DEB_VERSION=%{POSTGIS_DEB_VERSION}
POSTGIS_POSTGRESQL_DEB_VERSION=%{POSTGIS_POSTGRESQL_DEB_VERSION}

PROMETHEUS_VERSION=%{PROMETHEUS_VERSION}

RABBITMQ_VERSION=%{RABBITMQ_VERSION}

REDIS_VERSION=%{REDIS_VERSION}
REDIS_DEB_VERSION=%{REDIS_DEB_VERSION}

SBT_VERSION=%{SBT_VERSION}

TOMCAT9_VERSION=%{TOMCAT9_VERSION}
TOMCAT9_DEB_VERSION=%{TOMCAT9_DEB_VERSION}

ZIPKIN_VERSION=%{ZIPKIN_VERSION}

ZOOKEEPER_VERSION=%{ZOOKEEPER_VERSION}


JASPERREPORTS_SERVER_VERSION=%{JASPERREPORTS_SERVER_VERSION}
PENATHO_DI_VERSION=%{PENATHO_DI_VERSION}
