container_layer(
  name = "wget_buster",
  debs = ["//deps/buster:wget"],
  visibility = ["//test:__subpackages__"],
)

container_layer(
  name = "wget",
  debs = ["//deps/bullseye:wget"],
  visibility = ["//test:__subpackages__"],
)
