#!/bin/bash
set -e
set -o pipefail

if [ -d "$NEXUS_DATA" -a "$(stat -c '%U' "$NEXUS_DATA" 2>/dev/null)" = "root" ]; then
  chown nexus "$NEXUS_DATA"
  chmod o-rwx "$NEXUS_DATA"
fi

if [ "$1" = 'nexus' ]; then
  readonly nexus_data_conf="$NEXUS_DATA/etc"

  # the -Dapplication-conf nexus setting does nothing so add some config defaults
  if [ ! -d "$nexus_data_conf" ]; then
    gosu nexus mkdir -p "$nexus_data_conf"
    gosu nexus cp -a --no-clobber "$NEXUS_CONF/." "$nexus_data_conf"
  fi

  source /java-opts.sh

  exec gosu nexus java \
    -Dnexus-work=${NEXUS_DATA} \
    -Dnexus-webapp-context-path=${NEXUS_CONTEXT_PATH} \
    -cp 'conf/:lib/*' \
    ${JAVA_OPTS} \
    org.sonatype.nexus.bootstrap.Launcher ./conf/jetty.xml ./conf/jetty-requestlog.xml
else
  exec "$@"
fi
