#!/bin/bash
set -e
set -o pipefail

if [ -d "$TOMCAT_HOME" -a "$(stat -c '%U' "$TOMCAT_HOME" 2>/dev/null)" = "root" ]; then
  chown tomcat "$TOMCAT_HOME"
  chmod o-rwx "$TOMCAT_HOME"
fi

mkdir -p /var/cache/tomcat7/work
chown tomcat /var/cache/tomcat7/work

mkdir -p /etc/tomcat7/Catalina/localhost
chgrp -R tomcat /etc/tomcat7/Catalina/

cp --no-clobber /usr/share/tomcat7/skel/conf/* /etc/tomcat7/

if [ "$1" = 'tomcat' ]; then
  source /java-opts.sh
  export CATALINA_OPTS="$JAVA_OPTS"
  export JAVA_OPTS=""

  exec gosu tomcat "$CATALINA_HOME/bin/catalina.sh" run
else
  exec "$@"
fi
