#!/bin/bash
set -e
set -o pipefail

mkdir -p /var/cache/tomcat8/work
chown tomcat /var/cache/tomcat8/work

mkdir -p /etc/tomcat8/Catalina/localhost
chgrp -R tomcat /etc/tomcat8/Catalina/

cp --no-clobber /usr/share/tomcat8/skel/conf/* /etc/tomcat8/

if [ "$1" = 'tomcat' ]; then
  source /java-opts.sh
  export CATALINA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
  export JAVA_OPTS=""

  exec chroot --userspec=tomcat / "$CATALINA_HOME/bin/catalina.sh" run
else
  exec "$@"
fi
