#!/bin/bash
set -e
set -o pipefail

if [ -d "$ZOO_DATA_DIR" -a "$(stat -c '%U' "$ZOO_DATA_DIR" 2>/dev/null)" = "root" ]; then
  chown zookeeper "$ZOO_DATA_DIR"
  chmod o-rwx "$ZOO_DATA_DIR"
fi

if [ -d "$ZOO_DATA_LOG_DIR" -a "$(stat -c '%U' "$ZOO_DATA_LOG_DIR" 2>/dev/null)" = "root" ]; then
  chown zookeeper "$ZOO_DATA_LOG_DIR"
  chmod o-rwx "$ZOO_DATA_LOG_DIR"
fi

if [ "$1" = 'zookeeper' ]; then

  source /java-opts.sh

  # Write myid only if it doesn't exist
  if [[ ! -f "$ZOO_DATA_DIR/myid" ]]; then
    echo "${ZOO_MY_ID:-1}" > "$ZOO_DATA_DIR/myid"
  fi

  # from bin/zkEnv.sh
  CLASSPATH="$ZOOCFGDIR:$CLASSPATH"
  LIBPATH=("${ZOOBINDIR}"/../lib/*.jar)
  for i in "${LIBPATH[@]}"; do
    CLASSPATH="$i:$CLASSPATH"
  done

  exec chroot --userspec=zookeeper / java $JAVA_OPTS \
    -XX:OnOutOfMemoryError='kill -9 %p' \
    -cp "$CLASSPATH" \
    org.apache.zookeeper.server.quorum.QuorumPeerMain \
    "$ZOOCFGDIR/zoo.cfg"
else
  exec "$@"
fi
