#!/bin/bash
set -e
set -o pipefail

# kibana needs to be able to extract stuff to /var/lib/kibana/
if [ -d "$KIBANA_TEMP_DIR" -a "$(stat -c '%U' "$KIBANA_TEMP_DIR" 2>/dev/null)" = "root" ]; then
  chown kibana "$KIBANA_TEMP_DIR"
  chmod o-rwx "$KIBANA_TEMP_DIR"
fi

if [ "$1" = 'kibana' ]; then
  exec chroot --userspec=kibana / "$KIBANA_HOME/bin/kibana" "${@:2}"
else
  exec "$@"
fi
