#!/bin/bash
set -e
set -o pipefail

if [ -d "$GRAFANA_DATA" -a "$(stat -c '%U' "$GRAFANA_DATA" 2>/dev/null)" = "root" ]; then
  chown grafana "$GRAFANA_DATA"
  chmod o-rwx "$GRAFANA_DATA"
fi

if [ -d "$GRAFANA_LOGS" -a "$(stat -c '%U' "$GRAFANA_LOGS" 2>/dev/null)" = "root" ]; then
  chown grafana "$GRAFANA_LOGS"
  chmod o-rwx "$GRAFANA_LOGS"
fi

if [ "$1" = 'grafana' ]; then
  readonly conf_file="$GRAFANA_CONF/grafana.ini"

  if [ -z "$GF_SECURITY_ADMIN_PASSWORD" ]; then
    GF_SECURITY_ADMIN_PASSWORD=$(head -c 100 /dev/urandom | md5sum | awk '{print $1}')
    export GF_SECURITY_ADMIN_PASSWORD
    echo "Admin password has been set to: $GF_SECURITY_ADMIN_PASSWORD"
  fi

  exec chroot --userspec=grafana / /usr/sbin/grafana-server \
    --homepath="$GRAFANA_HOME" \
    --config="$conf_file" \
    cfg:default.paths.data="$GRAFANA_DATA" \
    cfg:default.paths.logs="$GRAFANA_LOGS" \
    cfg:default.paths.plugins="$GRAFANA_DATA/plugins"
else
  exec "$@"
fi
