#!/bin/bash
set -e
set -o pipefail

GRAFANA_WORK=/var/lib/grafana
adduser --system --uid=922 --home "$GRAFANA_WORK" grafana
if [ -d "$GRAFANA_WORK" -a "$(stat -c '%U' "$GRAFANA_WORK" 2>/dev/null)" = "root" ]; then
  chown grafana "$GRAFANA_WORK"
  chmod o-rwx "$GRAFANA_WORK"
fi

if [ "$1" = 'grafana' ]; then
  chown -R grafana /var/log/grafana

  exec gosu grafana /usr/sbin/grafana-server \
    --homepath=/usr/share/grafana \
    --config=/etc/grafana/grafana.ini \
    cfg:default.paths.data=/var/lib/grafana \
    cfg:default.paths.logs=/var/log/grafana
else
  exec "$@"
fi
