#!/bin/bash
set -e
set -o pipefail

if [ -d "$ES_DATA" -a "$(stat -c '%U' "$ES_DATA" 2>/dev/null)" = "root" ]; then
  chown elasticsearch "$ES_DATA"
  chmod o-rwx "$ES_DATA"
fi

if [ "$1" = 'elasticsearch' ]; then
  source /java-opts.sh

  # pull the bits from bin/elasticsearch.in.sh that have not been set by sourcing java-opts
  ES_CLASSPATH="$ES_HOME/lib/elasticsearch-$ES_VERSION.jar:$ES_HOME/lib/*"

  # Disables explicit GC
  JAVA_OPTS="$JAVA_OPTS -XX:+DisableExplicitGC"

  # Ensure UTF-8 encoding by default (e.g. filenames)
  JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"

  # Use our provided JNA always versus the system one
  JAVA_OPTS="$JAVA_OPTS -Djna.nosys=true"

  # the command bin/elasticsearch executes
  exec chroot --userspec=elasticsearch / java $JAVA_OPTS \
    -Djava.security.policy="$CONF_DIR/java.policy" \
    -Des.path.home="$ES_HOME" \
    -cp "$ES_CLASSPATH" \
    org.elasticsearch.bootstrap.Elasticsearch \
      -Epath.conf="$CONF_DIR" \
      -Epath.data="$DATA_DIR" \
      -Epath.logs="$LOG_DIR" \
      "${@:2}"
else
  exec "$@"
fi
