#!/bin/bash
set -e
set -o pipefail

if [ -d "$ES_DATA" -a "$(stat -c '%U' "$ES_DATA" 2>/dev/null)" = "root" ]; then
  chown elasticsearch "$ES_DATA"
  chmod o-rwx "$ES_DATA"
fi

if [ -d "$PLUGINS_DIR" -a "$(stat -c '%U' "$PLUGINS_DIR" 2>/dev/null)" = "root" ]; then
  chown elasticsearch "$PLUGINS_DIR"
  chmod o-rwx "$PLUGINS_DIR"
fi

if [ "$1" = 'elasticsearch' ]; then
  mkdir -p "$CONF_DIR/scripts"

  source /java-opts.sh

  # pull the bits from bin/elasticsearch.in.sh that have not been set by sourcing java-opts
  ES_CLASSPATH="$ES_HOME/lib/elasticsearch-$ES_VERSION.jar:$ES_HOME/lib/*"

  # Disables explicit GC
  JAVA_OPTS="$JAVA_OPTS -XX:+DisableExplicitGC"

  # Ensure UTF-8 encoding by default (e.g. filenames)
  JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"

  # Use our provided JNA always versus the system one
  JAVA_OPTS="$JAVA_OPTS -Djna.nosys=true"

  # the command bin/elasticsearch executes
  exec gosu elasticsearch java $JAVA_OPTS -cp "$ES_CLASSPATH" \
    -Des.path.home="$ES_HOME" \
    -Des.default.path.conf="$CONF_DIR" \
    -Des.default.path.data="$DATA_DIR" \
    -Des.default.path.logs="$LOG_DIR" \
    -Des.default.path.plugins="$PLUGINS_DIR" \
    org.elasticsearch.bootstrap.Elasticsearch start "${@:2}"
else
  exec "$@"
fi
