package(default_visibility = ["//visibility:public"])

container_layer(
  name = "gosu",
  files = ["@gosu//file"],
  directory = "/usr/local/bin",
  symlinks = { "/usr/local/bin/gosu": "/usr/local/bin/gosu-amd64" },
)
