package(default_visibility = ["//visibility:public"])

sh_binary(name = "add_user", srcs = ["add_user.sh"])
sh_binary(name = "add_group", srcs = ["add_group.sh"])

exports_files(["files/group", "files/passwd"])
