#!/bin/bash
set -e

for file in /etc/nginx/{conf.d,sites-enabled}/*; do
  if [ -f "$file" ]; then
    perl -p -e 's/(\$\{([A-Z0-9_]+)\})/defined $ENV{$2} ? $ENV{$2} : $&/eg' "$file" > "$file.new"
    mv "$file.new" "$file"
  fi
done

exec "$@"
