# container_image(
#   name = "elasticsearch_wget",
#   base = "//elasticsearch",
#   layers = ["//test:wget"],
# )
#
# container_test(
#   name = "elasticsearch",
#   size = "small",
#   image = ":elasticsearch_wget",
#   daemon = True,
#   mem_limit = "1024m",
#   test = "test.sh",
#   golden = "output.txt",
# )
