#!/bin/bash
set -e
set -o pipefail

if [ -d "$JENKINS_HOME" -a "$(stat -c '%U' "$JENKINS_HOME" 2>/dev/null)" = "root" ]; then
  chown jenkins "$JENKINS_HOME"
  chmod o-rwx "$JENKINS_HOME"
fi

# Copy files from /usr/share/jenkins/ref into /var/jenkins_home
# So the initial JENKINS_HOME is set with expected content.
# Don't override, as this is just a reference setup, and use from UI
# can then change this, upgrade plugins, etc.
copy_reference_file() {
  f="${1%/}"
  rel="${f:23}"
  dir="$(dirname ${f})"
  mkdir -p "$JENKINS_HOME/${dir:23}"

  if [[ ${rel} == plugins/*.hpi ]]; then
    plugin=${rel%.hpi}
    cp -r "/usr/share/jenkins/ref/${rel}" "$JENKINS_HOME/${plugin}.jpi";
    rel="${plugin}.jpi"
  else
    cp -r "/usr/share/jenkins/ref/${rel}" "$JENKINS_HOME/${rel}";
  fi
  # pin plugins on initial copy
  [[ ${rel} == plugins/*.jpi ]] && touch "$JENKINS_HOME/${rel}.pinned"
}
export -f copy_reference_file

if [ "$1" = 'jenkins' ]; then
  find /usr/share/jenkins/ref/ -type f -exec gosu jenkins bash -c "copy_reference_file '{}'" \;

  source /java-opts.sh

  exec gosu jenkins java ${JAVA_OPTS} -jar /usr/share/jenkins/jenkins.war $JENKINS_OPTS
else
  exec "$@"
fi
