package(default_visibility = ["//scripts:__subpackages__"])

sh_library(name = "bazel_functions", srcs = ["bazel_functions.sh"])

sh_binary(
  name = "build_container",
  srcs = ["build_container.sh"],
  visibility = ["//visibility:public"],
)
