sh_library(
  name = "bazel_functions",
  srcs = ["bazel_functions.sh"],
  visibility = ["//visibility:public"],
)

sh_binary(
  name = "build_container",
  srcs = ["build_container.sh"],
  visibility = ["//visibility:public"],
)
